# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

jobs:
  # Single deploy job since we're just deploying
  build-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checks out your repository and download it
      - name: Setup Node.js
        uses: actions/setup-node@v1 #install node (for access to npm command)
        with:
          node-version: '12'
      - uses: actions/cache@v2 # This action allows caching dependencies and build outputs to improve workflow execution time.
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }} # An explicit key for restoring and saving the cache ?
          restore-keys: ${{ runner.os }}-node- # An ordered list of keys to use for restoring the cache if no cache hit occurred for key ?
      - run: npm ci # install project dependencies
      - run: npm run build --if-present # build the project
      - uses: netlify/actions/cli@master # This Action enables arbitrary actions with the Netlify CLI
        env: # environment variables used for netlify action
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_API_ID }}
        with: # A map of the input parameters defined by the action. Each input parameter is a key/value pair. 
          args: deploy --dir=dist --prod
